### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by snelweg** [knipknap/better-tool-library#12]
As I understood the main reason your great Library tool will not  be included into FreeCAD/main is that there are hard-coded 'names' in the images.

Might this help:
https://graphicdesign.stackexchange.com/questions/62618/multilingual-svg-for-the-web
```
Support for this in SVG renderers is not universal, so don't rely on it, but where it works it works:

<switch>
  <text systemLanguage="de">Das ist der übersetzte Text auf Deutsch</text>
  <text>This is the default text in English</text>
</switch>

```

https://stackoverflow.com/questions/53775440/switch-the-display-language-of-multi-language-svg-using-systemlanguage-for-dis

It would be real nice to have the BTL in FreeCAD!

**Comment by knipknap** [comment]
I agree, but I already proposed using SVG i18n to the FreeCAD Path workbench owner and it didn't seem to address his concerns. Honestly I still don't understand the issue, as unlike SVG, his proposal of using the FreeCAD attribute names doesn't solve the i18n nor sketch dimension label issue at all, as the attributes aren't translatable.

Anyway, I felt there was too much fruitless discussion, and in the end it is on the FreeCAD Path workbench owner to decide if BTL should be included. Probably not much I can do about it.
