### ISSUE TITLE
Toolbar Icon won't stay after restart.

### ISSUE THREAD

**Issue by Connor9220** [knipknap/better-tool-library#19]
After placing the BTL icon where I want it, and restarting FreeCAD, it moves back to very top.
![Screenshot from 2024-01-21 14-51-31](https://github.com/knipknap/better-tool-library/assets/833255/f4bc8b2c-31df-4d33-8b0c-454f13f3ea51)

Additionally, would be nice if it had a Tooltip when you hover over it like others, and if you right click on the toolbars, the name for the btl icon isn't present next to its check mark.  I couldn't grab a screen shot of this.  

Using v0.21.2 FreeCAD

**Comment by knipknap** [comment]
I am not really sure how that works, but tried a fix. Let me know if the problem persists after an upgrade to latest master.
