### ISSUE TITLE
Proposed fix to fusionserializer.py (in serializers)

### ISSUE THREAD

**Issue by ShamanTcler** [knipknap/better-tool-library#21]
Issue: When material was carbide in the JSON file the record was still coming in HSS.

Fix:
    - Simplify logic
    - Always make string compares to lowercase. So Carbide, CARBIDE and CArbide all work

Around line 260, replace material assignment code with:

'''
            # default material to hss. fusion allows for ceramics or unspecified
            # tool materials, While  FreeCad currently only allow for Carbide and HSS
            # default set to HSS change is Carbide

            tool.shape.set_material(HSS)
            tool.set_material(HSS)

            if  toolitem["BMC"].lower() == "carbide":
                tool.shape.set_material(Carbide)
                tool.set_material(Carbide)
'''

**Comment by knipknap** [comment]
I pushed a similar fix. Please reopen if the problem persists.
