### ISSUE TITLE
Feed and speed not work

### ISSUE THREAD

**Issue by rmaltais** [knipknap/better-tool-library#29]
I can't use this feature. When i select DOC and WOC always stay in certain percentage... Nothing happend after long time.

[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: French/Canada (fr_CA)
Installed mods: 
  * btl 0.9.9
[/code]

**Comment by knipknap** [comment]
I'm afraid your report does not include enough information to find out what may be going on. Could you post a screenshot of the tool parameters, and another of the machine settings, and one of the calculator?

**Comment by rmaltais** [comment]
Hi,
Sorry for not giving enough information. In fact, it is only in adatative mode that the calculator does not work. Here are the screenshots of the settings.

![FreeCAD_VgzZPvWXjd](https://github.com/knipknap/better-tool-library/assets/41405404/b643127c-15ce-4d0f-b572-f24d38d8a1cd)
![FreeCAD_raZQ4r3QkY](https://github.com/knipknap/better-tool-library/assets/41405404/5856369d-be80-439b-a98f-37949ae44eb5)
![FreeCAD_sWl3wMGnMo](https://github.com/knipknap/better-tool-library/assets/41405404/f339188d-b734-47c1-a3de-f1203df682cf)

thank

**Comment by knipknap** [comment]
Wow, looks like you had to dig pretty deep for this one, thank you! It's merged, so should work if you update.

**Comment by Arm4g3ddon** [comment]
@knipknap Thanks man! Yeah a lot of back and forth but then I realized it was the method :)
