### ISSUE TITLE
Tool Editor in FreeCad. 

### ISSUE THREAD

**Issue by marblemonster** [knipknap/better-tool-library#34]
Have 0.21 ...No Tool editor. Unable to alter existing tools. Wasn't able to import BTL
I have also not offset capabilities and the simulation cut is not complete.

**Comment by Arm4g3ddon** [comment]
Hello marblemonster,

could you provide more Information? You can do this in FreeCad with Help -> About FreeCad -> Copy to Clipboard
Have you installed BTL via the Plugin Manager of FreeCad?

**Comment by marblemonster** [comment]
Hi Tim,
Thanks for responding. I have tried to install BTL without success. My Tool
Dock does not respond with the create tool feature. I am sent to select a
shape and there it ends.
Even in Operations cant select any tools i tried to create.

**Comment by Arm4g3ddon** [comment]
OK, have you created a Library first and selected it on the bottom left?

**Comment by marblemonster** [comment]
Never got it to work. I'm a Fushion 360 guy, and was looking for a less
expensive software for my 3D printing.
