### ISSUE TITLE
`UserWarning: Setuptools is replacing distutils` when loading BetterToolLibrary - AddOn

### ISSUE THREAD

**Issue by reneas** [knipknap/better-tool-library#45]
Every time I start FreeCAD with the BTL AddOn enabled I get the following output in red in my report view:

```
/usr/lib/python3.11/site-packages/_distutils_hack/__init__.py:32: UserWarning: Setuptools is replacing distutils.
Support for replacing an already imported distutils is deprecated. In the future, this condition will fail.
Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
```

But then it also says:

```
Better Tool Library v0.9.9-70-g2594eb9 loaded successfully.
```

The part that makes me worry is the `In the future, this condition will fail.`

So should I worry?

**Comment by knipknap** [comment]
Are you sure that this is caused by BTL? BTL does not use distutils, so I think this is probably an issue somewhere else.

**Comment by reneas** [comment]
It was only ocurring when i activated the BTL AddOn so I figured it caused it. But now with version 1.0 released it no longer occurs!

**Comment by knipknap** [comment]
Great, thanks for the feedback.
