### ISSUE TITLE
README: Prereqs

### ISSUE THREAD

**Issue by luzpaz** [knipknap/better-tool-library#47]
In https://github.com/knipknap/better-tool-library?tab=readme-ov-file#prerequisites we see: 

> Better Tool Library (BTL) is compatible with FreeCAD 0.19, 0.21, and 0.22.

1. No mention of 1.0.0 ?
2. Perhaps it's better to state it this way and therefore omitting the need to specify all subsequent versions since 0.19

> Better Tool Library (BTL) is compatible with FreeCAD ≥ v0.19

**Comment by knipknap** [comment]
Thanks for pointing it out! It's fixed.
