### ISSUE TITLE
Adding Vendors catalogs

### ISSUE THREAD

**Issue by ShamanTcler** [knipknap/better-tool-library#7]
I was looking for your import file format specs, and don't see them. (I did look under docs)

I would like to bring in catalogs from Whiteside & Bits&Bits.

Is there a JSON or such format you prefer? ( I already can make FreeCad tools and libraries but your BTL stuff is a mystery)

I know in a previous chat I said I was using CSV or Excel from vendors, because frankly most vendors don't understand anything more than that.

**Comment by knipknap** [comment]
Actually just implemented the UI for the Camotics importer, so now its even easier to add your own importer:

1. Add a serializer in `btl/serializers/`. For example, `whitesideserializer.py`. The serializer would look similar to [camoticsserializer.py](https://github.com/knipknap/better-tool-library/blob/main/btl/serializers/camoticsserializer.py), but you can leave out unsupported methods. In other words, if you want to only support import and no export, you don't have to implement any `serialize*()` methods.
2. Add your serializer to the list in `btl/serializers/__init__.py`

Done. It should automatically appear in the UI, meaning, when you click "File -> Import library", your serializer should show up in the file filter dropdown box of the file selector.
